# Generated by Django 2.1.3 on 2018-12-01 07:56

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('reg_number', models.CharField(max_length=40, unique=True)),
                ('publish_date', models.DateTimeField(verbose_name='publish date')),
                ('sign_date', models.DateField(verbose_name='sign date')),
                ('protocol_date', models.DateField(verbose_name='protocol date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='price')),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'Rubble'), (1, 'Dollar'), (2, 'Euro')], default=0, verbose_name='currency')),
                ('current_stage', models.PositiveSmallIntegerField(choices=[(0, 'Исполнение'), (1, 'Исполнение завершено'), (2, 'Исполнение прекращено'), (3, 'Аннулирован')], db_index=True, default=0)),
                ('region_code', models.PositiveSmallIntegerField(verbose_name='region code')),
                ('contract_url', models.URLField(verbose_name='contract url')),
                ('number', models.CharField(max_length=20, verbose_name='number document')),
                ('description', models.TextField(help_text='documentBase field in API', verbose_name='full description')),
                ('provider_id', models.BigIntegerField(db_index=True, verbose_name='ext provider id')),
                ('ext_mongo_id', models.UUIDField(unique=True, verbose_name='external mongo_id')),
                ('fz', models.PositiveSmallIntegerField(verbose_name='fz')),
                ('form', models.URLField(max_length=255, verbose_name='print form')),
                ('okpd2okved2', models.BooleanField(default=False)),
                ('execution_dt', django.contrib.postgres.fields.ranges.DateRangeField(verbose_name='Date start and end')),
                ('meta_data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='meta data response contract')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('reg_number', models.CharField(max_length=40, unique=True)),
                ('kpp', models.IntegerField(verbose_name='kpp')),
                ('inn', models.IntegerField(verbose_name='inn')),
                ('name', models.TextField(verbose_name='description')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('reg_number', models.CharField(max_length=40, unique=True)),
                ('product_str', models.TextField(verbose_name='full text product')),
                ('paid_price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='paid rub')),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, 'Rubble'), (1, 'Dollar'), (2, 'Euro')], default=0, verbose_name='currency')),
                ('vat_price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='paid rub')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('reg_number', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('sid', models.CharField(max_length=40, verbose_name='sid')),
                ('okei', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80, verbose_name='name and code'), size=None)),
                ('okpd2', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80, verbose_name='name and code'), size=None)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-price'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('customer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='contracts.Customer')),
                ('participant', models.CharField(max_length=6, verbose_name='participant type')),
                ('contact_info', models.CharField(max_length=255, verbose_name='full name of supplier')),
                ('legal_form', models.CharField(max_length=255, verbose_name='code and name')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
            bases=('contracts.customer',),
        ),
    ]
