# Generated by Django 2.1.3 on 2018-12-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execution',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution', to='core.PaymentDocument', verbose_name='document'),
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contracts.Customer', verbose_name='customer of contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='suppliers',
            field=models.ManyToManyField(related_name='contracts', to='contracts.Supplier'),
        ),
    ]
