# Generated by Django 2.1.3 on 2018-12-01 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_auto_20181201_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='execution',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.Execution'),
            preserve_default=False,
        ),
    ]
