# Generated by Django 2.1.3 on 2018-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_auto_20181201_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='ext_mongo_id',
            field=models.CharField(max_length=80, unique=True, verbose_name='external mongo_id'),
        ),
    ]
