# Generated by Django 2.1.3 on 2018-12-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20181201_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.BigIntegerField(verbose_name='inn'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='kpp',
            field=models.BigIntegerField(verbose_name='kpp'),
        ),
    ]
