# Generated by Django 2.1.3 on 2018-12-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20181201_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='execution',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
