# Generated by Django 2.1.3 on 2018-12-01 09:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_auto_20181201_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='geometry location'),
        ),
    ]
