# Generated by Django 2.1.3 on 2018-12-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_customer_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=80, verbose_name='number document'),
        ),
    ]
