# Generated by Django 2.1.3 on 2018-12-01 09:57

import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0010_auto_20181201_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='execution_dt',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True, verbose_name='Date start and end'),
        ),
    ]
