# Generated by Django 2.1.3 on 2018-12-01 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_auto_20181201_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.Execution'),
        ),
    ]
