# Generated by Django 2.1.3 on 2018-12-01 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_auto_20181201_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='protocol_date',
            field=models.DateField(blank=True, null=True, verbose_name='protocol date'),
        ),
    ]
