# Generated by Django 2.1.3 on 2018-12-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0013_auto_20181201_1000'),
        ('contracts', '0004_auto_20181201_0919'),
    ]

    operations = [
    ]
