# Generated by Django 2.1.3 on 2018-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0014_merge_20181201_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='provider_id',
            field=models.CharField(db_index=True, max_length=100, verbose_name='ext provider id'),
        ),
    ]
