# Generated by Django 2.1.3 on 2018-12-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0015_auto_20181201_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_url',
            field=models.URLField(null=True, verbose_name='contract url'),
        ),
    ]
