# Generated by Django 2.1.3 on 2018-12-01 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_updated', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Date updated')),
                ('reg_number', models.CharField(max_length=40, unique=True)),
                ('published_content', models.UUIDField(verbose_name='file identifier')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('type', models.PositiveSmallIntegerField(choices=[(2, 'Scan'), (0, 'Payment'), (1, 'Receipt')], default=0, verbose_name='file type')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
                'ordering': ['published_content'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('date_created', models.DateField(verbose_name='Date created')),
                ('number', models.BigIntegerField(default=0, verbose_name='number')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
