# Generated by Django 2.1.3 on 2018-12-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='reg_number',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
