# Generated by Django 2.1.3 on 2018-12-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_auto_20181201_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contracts.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOkpd2Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okpd2', models.CharField(max_length=80, verbose_name='okpd2 code')),
                ('score', models.IntegerField()),
            ],
        ),
    ]
